@startuml

skinparam class {
	BackgroundColor PaleGreen
	BorderColor Green
	ArrowColor black
	FontSize 28
	BackgroundColor<<USP>> Pink
	BorderColor<<USP>> HotPink
}

skinparam backgroundColor Linen
skinparam linetype ortho
skinparam shadowing true
skinparam minClassWidth 200
skinparam LegendBackgroundColor Strategy
skinparam LegendBorderThickness 0
skinparam LegendFontSize 20
skinparam defaultFontSize 20
skinparam Padding 8
skinparam Nodesep 150
skinparam ArrowThickness 2
skinparam ArrowColor DarkSlateGray

hide methods
hide empty members
hide circle

package "MyCargonaut | domain diagram" <<Frame>> {

class User {
    name
    geburtsdatum
    profilbild
    email
    passwort
}

class Client {

}
class Fahrer {

}

Client -up-|> User
Fahrer -up-|> User


Client -down-|> Session
Fahrer -down-|> Session

class Session {
  abfahrtsOrt
  destination
  abfahrtsZeit
  bezahlung
  Status
}
class ClientSession {
  suche
}

class FahrerSession {
   Biete
   Fahrzeugverwaltung
}
ClientSession -up-|> Session
FahrerSession -up-|> Session

class Profil {
  name
  geburtsdatum
  profilbild
  email
  passwort
  bewertung
}

Session *-right- Profil
class Status {
  farht
  expedition
}
Status -right- Session

}


legend right
  | <img src="../../src/assets/Export/150×45/resizecar_android_MyCargonautmdpi.png"> |= \n\n »MyCargonaut« |
  | Produktion | [[https://cargonaut-a2624.web.app/]] |
  | Repository | [[https://github.com/yanv022/MyCargonaut]] |
  | UML-Tool| PlantUML v1.2019.5|
  | Ersteller| Yann Abel Ndemmeze Vougue|
  | Mail| yann.abel.ndemmeze.vougue@mni.thm.de |
  | Letzte Änderung| 21.06.2022 |
end legend

@enduml
