# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ nodepipeAndDeployment ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARGONAUT_A2624 }}'
          channelId: live
          projectId: cargonaut-a2624


    #  - name: Deploy
    #    uses: JamesIves/github-pages-deploy-action@v4.3.3
    #    with:
    #      token: ${{ secrets.GITHUB_TOKEN }}
    #    branch: gh-pages # The branch the action should deploy to.
    #    folder: client/dist/kmsgruppe3 # The folder the action should deploy.
